# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

<<<<<<< HEAD
title: neoXena
=======
title: neoXena.dev
logo: /assets/images/neoxena-logo-v2-170x42.png
>>>>>>> 06c3911 (First post!)
email: michael.cahill@neoxena.dev
description: >- # this means to ignore newlines until "baseurl:"
  Hirundo neoxena -- welcome swallow.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://neoxena.dev" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: ""
github: [metadata]
github_username:  neoxena

minimal_mistakes_skin: default
<<<<<<< HEAD
search: false
=======
search: true

lunr:
  search_within_pages: true
>>>>>>> 06c3911 (First post!)

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Australia/Sydney # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Include in processing.
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
<<<<<<< HEAD
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
=======
exclude:
#   - .sass-cache/
  - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
  - vendor
  - .obsidian
>>>>>>> 06c3911 (First post!)

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji 
  - jekyll-include-cache

author:
  name: "Michael Cahill"
  avatar: "/assets/images/mjc-small.jpg"
<<<<<<< HEAD
  bio: "Plumber of bits"
  links:
    - label: "LinkedIn"
      icon: "fas fa-fw fa-linkedin"
=======
  bio: "Two bit plumber"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
>>>>>>> 06c3911 (First post!)
      url: "https://www.linkedin.com/in/michaeljcahill/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/michaelcahill"

footer:
  links:
    - label: "LinkedIn"
<<<<<<< HEAD
      icon: "fas fa-fw fa-linkedin"
=======
      icon: "fab fa-fw fa-linkedin"
>>>>>>> 06c3911 (First post!)
      url: "https://www.linkedin.com/in/michaeljcahill/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/michaelcahill"

# Default settings
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      related: true
<<<<<<< HEAD
=======
      share: true
>>>>>>> 06c3911 (First post!)
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
<<<<<<< HEAD
=======
posts_archive:
  type: liquid
  path: /posts/
>>>>>>> 06c3911 (First post!)
tag_archive:
  type: liquid
  path: /tags/
